- samples/csharp/dotnet-windows/speechtotext-wpf/speechtotext-wpf/MainWindow.xaml.cs
* I thought it's mismatch to set  RecognizedEventHandler to recognizingHandler.
```
[x] Bugfix
[ ] Feature
```
> fix incorrect event handler registered for Recognizing event in speechtotext-wpf sample.

- quickstart/text-to-speech/csharp-uwp/helloworld/MainPage.xaml.cs
- Removed an extraneous "yet".
- Removed "// Native playback support will be added in the future release.", a future promise that shouldn't appear.
- Fixed a typo: "user MediaPlayer to play it" should be "use MediaPlayer to play it".
Fixed two typos and got rid of a future promise in the code comments.
```
[ ] Bugfix
[ ] Feature
```
> 1558066: Changes in code comments

- samples/csharp/sharedcontent/console/Program.cs
- samples/csharp/sharedcontent/console/speech_recognition_samples.cs
Adding Sample for showing a possible candidate for switching region
* ...
Adding a new sample.
```
[ ] Bugfix
[ ] Feature
```
> Adding Sample for showing a possible candidate for switching region

- samples/java/jre/console/src/com/microsoft/cognitiveservices/speech/samples/console/SpeechRecognitionSamples.java
- samples/java/jre/console/src/com/microsoft/cognitiveservices/speech/samples/console/TranslationSamples.java
- samples/java/jre/console/src/com/microsoft/cognitiveservices/speech/samples/console/WavStream.java
* Fix issue #874. Properly handle shorter read buffers at the end of the WAV file.
* Suppress two warnings of unused variables (they are required for code readability)
* Resolve one warning of unused import
```
[x ] Bugfix
[ ] Feature
```
> Java Sample: Fix logic for reading from a FileInputStream and other minor issues

- samples/csharp/uwp/speechtotext-uwp/README.md
- samples/java/jre/console/src/com/microsoft/cognitiveservices/speech/samples/console/SpeechRecognitionSamples.java
- samples/java/jre/console/src/com/microsoft/cognitiveservices/speech/samples/console/WavStream.java
Fix for issue #1231. Speech SDK input stream can support 8khz. However, the WavStream.java WAV parser code does not allow it, and our sample code always creates the input stream using default format (which is 16khz). With this change I allow parsing 8khz WAV files and creating an input stream on the recognizer while explicitly setting its format to allow both 16khz and 8khz streams. Tested with my own WAV files at both sample rates.
Thanks you #carlossapnucivicom for reporting this issue!
Also fix broken sentence in an unrelated document.
```
[x ] Bugfix
[ ] Feature
```
> Allow 8khz WAV input stream in Java console sample

- quickstart/java/jre/virtual-assistant/pom.xml
Our internal tools alerted us of a security risk that requires an update of the Bouncy Castle Crypto Maven package, in the virtual-assistant quick-start sample.
Tested with our internal "echo-bot" to make sure there is no regression after this change.
Link to the relevant Maven package: https://mvnrepository.com/artifact/org.bouncycastle/bcprov-jdk15on
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Update one of the Maven packages to latest version
```
> Fix security alert in virtual-assistant Java quick-start

- samples/csharp/sharedcontent/console/Program.cs
This was a result of bad merge following the update of samples for the 1.20 release.
> Fix build break in C# sample

- ci/build.yml
- samples/csharp/sharedcontent/console/Program.cs
The fix was confirmed in the first commit of this PR, where I intentionally introduced a build break in the C# sample. This is a link to the build, and you see that it is red: https://msasg.visualstudio.com/Skyman/_build/results?buildId=26975675&view=results
> Fix YML script such that a build break in VS builds will be logged as task failure and will block check-in

- samples/ingestion/ingestion-client/Setup/ArmTemplateBatch.json
- samples/ingestion/ingestion-client/StartTranscriptionByTimer/StartTranscriptionHelper.cs
There's was a bug introduced here
https://github.com/Azure-Samples/cognitive-services-speech-sdk/commit/74c104ab5b102c8d41270f1569fe2ea88b5cbf78
that would result in most service bus messages processed by the StartTranscriptionFunction not being completed (as only the nth message of each chunk would be completed).
This PR fixes it by completing all processed messages.
We didn't notice that bug earlier, since we by default have a maxDeliveryCount of 1 on start transcription service bus messages - so the additional messages would get dead lettered. However, if the maxDeliveryCount is being increased, it would lead to the same service bus message being processed twice.
```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local …
```
> [IngestionClient] Fix StartTranscriptionHelper service bus message completion bug

- samples/ingestion/ingestion-client/Connector/BatchClient.cs
- samples/ingestion/ingestion-client/FetchTranscription/TextAnalytics/TextAnalyticsProvider.cs
- samples/ingestion/ingestion-client/FetchTranscription/TranscriptionProcessor.cs
- samples/ingestion/ingestion-client/Setup/ArmTemplateBatch.json
- samples/ingestion/ingestion-client/Setup/ArmTemplateRealtime.json
- samples/ingestion/ingestion-client/StartTranscriptionByTimer/StartTranscriptionHelper.cs
* Fix bug: Http request retry in Polly was trying to re-use the same HttpRequest - needs to be recreated
* Fix bug: We might run into NRE exceptions if we got only AudioLevelRequests OR UtteranceLevelRequests
* Prepare scenario in which the same audio file is processed twice (which might happen if a message lock is lost, for instance if the function is restarted during processing - or if the audio file is deleted and then re-uploaded).
```
[x] Bugfix
[ ] Feature
```
> [IngestionClient] Fix http request retry, text analytics NRE and prepare for same service bus message on retry

- samples/ingestion/ingestion-client/Connector/BatchClient.cs
- samples/ingestion/ingestion-client/FetchTranscription/TranscriptionProcessor.cs
- samples/ingestion/ingestion-client/Setup/ArmTemplateBatch.json
- samples/ingestion/ingestion-client/Setup/ArmTemplateRealtime.json
* Retry on HttpStatusCodeException 
* Catch Http exceptions when downloading files to blob, and write error message instead of failing the complete job
```
[x] Bugfix
[ ] Feature
```
> [IngestionClient] Retry HttpStatusCodeException and do not fail whole transcription on transcript download failure

- samples/js/browser/.npmrc
- samples/js/browser/index.html
Users attempting an npm install (as per readme instructions) will get an auth error, since the skyman npm package registry is specified in the included .npmrc file (which is not needed). Also added token renewal code for long running scenarios.
* ...
```
[ x] Bugfix
[ ] Feature
```
> Delete .npmrc, add token renewal

- samples/python/console/speech_sample.py
The previous paragraph-accuracy score with the continuous mode is not aligned with our speech assessment score engine when `miscue` is enabled. So we update it and make it the same with our engine.
```
[x] Bugfix
[ ] Feature
```
> fix: update paragraph accuracy score and make it algin with the engine

- samples/python/console/speech_sample.py
The previous paragraph-accuracy score with the continuous mode is not aligned with our speech assessment score engine when `miscue` is enabled. So we update it and make it the same with our engine.
```
[x] Bugfix
[ ] Feature
```
> fix: update paragraph-accuracy score and make it aligned with the engine

- samples/cpp/embedded-speech/samples/intent_recognition_samples.cpp
- samples/csharp/dotnetcore/embedded-speech/samples/IntentRecognitionSamples.cs
- samples/java/android/embedded-speech/app/build.gradle
- samples/java/jre/embedded-speech/src/com/microsoft/cognitiveservices/speech/samples/embedded/IntentRecognitionSamples.java
Improve the keyword pattern in embedded intent recognition samples to work also with commas, and add the `@aar` package specifier in the Android embedded speech sample `build.gradle`.
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Enhancement.
```
> Update embedded speech samples

- samples/java/jre/console/src/com/microsoft/cognitiveservices/speech/samples/console/SpeechRecognitionSamples.java
The public LID document https://learn.microsoft.com/en-us/azure/cognitive-services/speech-service/language-identification?tabs=continuous&pivots=programming-language-java was including the wrong Java sample. Move the doc tags to the right location to show the correct Java sample (continuous SR with continuous LID). I will do the equivalent change in the internal MS repo.
> Fix doc tag for LID Java sample

- quickstart/javascript/node/conversation-transcription/index.js
- quickstart/javascript/node/conversation-transcription/package.json
- quickstart/javascript/node/from-file/index.js
- quickstart/javascript/node/from-file/package.json
- quickstart/javascript/node/meeting-transcription/index.js
- quickstart/javascript/node/meeting-transcription/package.json
- quickstart/javascript/node/speaker-recognition/identification/independent-identification.js
- quickstart/javascript/node/speaker-recognition/identification/package.json
- quickstart/javascript/node/speaker-recognition/verification/dependent-verification.js
- quickstart/javascript/node/speaker-recognition/verification/package.json
- quickstart/javascript/node/text-to-speech/index.js
- quickstart/javascript/node/text-to-speech/package.json
- samples/js/node/filePushStream.js
- samples/js/node/index.js
- samples/js/node/intent.js
- samples/js/node/micSTT.js
- samples/js/node/package.json
- samples/js/node/pronunciationAssessment.js
- samples/js/node/pronunciationAssessmentConfiguredWithJson.js
- samples/js/node/pronunciationAssessmentContinue.js
- samples/js/node/pronunciationAssessmentFromMicrophone.js
- samples/js/node/settings.js
- samples/js/node/speech.js
- samples/js/node/synthesis.js
- samples/js/node/translation.js
* ...
allow sample js to work with ESM v1.33.1
```
[ ] Bugfix
[ ] Feature
[ x] Documentation content changes
```
> initial changes to allow sample js to work with ESM v1.33.1

- ci/build.yml
pipeline failed.
> ##[error]C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\33.0.95\targets\Microsoft.Android.Sdk.Tooling.targets(20,5): Error XA0031: Java SDK 11.0 or above is required when using .NET 6 or higher. Download the latest JDK at: https://aka.ms/msopenjdk
```
[x] Bugfix
[ ] Feature
```
> install JDK 17 to fix dotnet build

- samples/ingestion/ingestion-client/.devcontainer/devcontainer.json
- samples/ingestion/ingestion-client/.github/dependabot.yml
- samples/ingestion/ingestion-client/.gitignore
- samples/ingestion/ingestion-client/StartTranscriptionByTimer/README.md
- samples/ingestion/ingestion-client/StartTranscriptionByTimer/StartTranscriptionByTimer.csproj
This PR adds a devcontainer to the ingestion-client. Additionally, it adds instructions to run the StartTranscriptionByTimer function locally.
If we're happy with this change, I will follow this up with similar changes for the other functions under the ingestion-client in a subsequent PR. 
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Configuration and documentation for developer experience.
```
> Make it easy to run StartTranscription function locally for development.

- samples/ingestion/ingestion-client/Setup/ArmTemplateBatch.json
Ingestion Client github action fails with error
`parse error: Expected another key-value pair at line 246, column 5`
https://github.com/Azure-Samples/cognitive-services-speech-sdk/actions/runs/9578456021/job/26408749002
```
[x] Bugfix
[ ] Feature
```
> [IngestionClient] Fix ArmTemplateBatch.json invalid json

- samples/ingestion/ingestion-client/Setup/ArmTemplateBatch.json
This PR adds an empty-string default value to the deployment parameter `CompletedServiceBusConnectionString` to make it an optional parameter during deployment.  
```
[ ] Bugfix
[ ] Feature
[x] Other... Deployment config changes
```
> [IngestionClient] Make the CompletedServiceBusConnectionString an optional deployment parameter

- samples/ingestion/ingestion-client/Setup/ArmTemplateBatch.json
- samples/ingestion/ingestion-client/Setup/ArmTemplateRealtime.json
Fixes an issue with CompletedServiceBusConnectionString being used incorrectly as a variable. It is now being used correctly as a parameter. 
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Deployment config changes.
```
> [IngestionClient] Fix ARM batch template to use CompletedServiceBusConnectionString as a parameter, not a variable. 

- samples/ingestion/ingestion-client/Setup/ArmTemplateBatch.json
- samples/ingestion/ingestion-client/Setup/ArmTemplateRealtime.json
- samples/ingestion/ingestion-client/Setup/guide.md
- samples/ingestion/ingestion-client/StartTranscriptionByTimer/StartTranscriptionByTimer.cs
- samples/ingestion/ingestion-client/StartTranscriptionByTimer/StartTranscriptionEnvironmentVariables.cs
* Resolves #2448 
* This PR adds timer schedule as a configurable parameter for the StartTranscriptionByTimer azure function while deploying Ingestion Client. It sets the default value to `0 */2 * * * *` (2 minutes)
```
[ ] Bugfix
[x] Feature
```
> feat: Time interval as a parameter while deploying for StartTranscriptionByTimer function
