Azure-Samples/cognitive-services-speech-sdk

Windows/quickstart-csharp/Program.cs

* ...
```
[ ] Bugfix
[ ] Feature
```

update for june release in helloworld

---

.gitattributes
ci/build.yml
ci/functions.sh
ci/patch-samples.pl

Initial build definition

---

samples/cpp/windows/console/README.md
samples/cpp/windows/console/samples/intent_recognition_samples.cpp
samples/csharp/dotnet-windows/console/README.md
samples/csharp/dotnetcore-windows/console/README.md
samples/csharp/sharedcontent/console/intent_recognition_samples.cs
samples/java/android/sdkdemo/README.md
samples/java/android/sdkdemo/app/src/main/java/com/microsoft/cognitiveservices/speech/samples/sdkdemo/MainActivity.java

Clarify that for LUIS the endpoint key is needed

---

docs/breaking_changes_1_0_0.md

* ...
```
[ ] Bugfix
[ ] Feature
```

another fix

---

quickstart/csharp-uwp/README.md

* Just wanted to make it more clear what they are supposed to do. First click the top button, then click the bottom and start speaking.
```
[ ] Bugfix
[ ] Feature
```

Added to run instructions

---

quickstart/csharp-dotnet-windows/README.md

* Specified they should use Speech (preview) and not Speech Recognition as their Azure resource. It's confusing which one to use, because the code itself has a RecognizeSpeechAsync(). Yet, we don't use the recognition resource.
```
[ ] Bugfix
[ ] Feature
[ x] Documentation content changes
```

Clarified which Speech resource to use

---

quickstart/csharp-dotnet-windows/README.md

* I had created my Speech resource long ago, so did not realize it said WestUS2, and when I added a region to my sample, I used "westus". So I had to recreate my resource. Others might go through this.
```
[ ] Bugfix
[ ] Feature
[ x] Documentation content changes
```

Added detail about Speech resource/region

---

samples/csharp/uwp/speechtotext-uwp/README.md

* There was no .wav file included in this sample, so I provided a link to the weather .wav file from another sample. The user might not remember where that was exactly to look for it themselves.
```
[ ] Bugfix
[ ] Feature
```

Added .wav file link

---

docs/breaking_changes_1_0_0.md
quickstart/csharp-uwp/README.md
quickstart/js-browser/README.md
quickstart/js-browser/index.html
samples/csharp/uwp/speechtotext-uwp/README.md
samples/java/jre/console/src/com/microsoft/cognitiveservices/speech/samples/console/WavStream.java

* Tune READMEs.
* JavaScript quickstart: fix language property name.
* Add C++ section to breaking changes page.

Various updates

---

quickstart/objectivec-ios/helloworld/helloworld.xcodeproj/project.pbxproj
quickstart/objectivec-ios/helloworld/helloworld/Base.lproj/Main.storyboard
quickstart/objectivec-ios/helloworld/helloworld/ViewController.m
quickstart/objectivec-ios/helloworld/helloworldUITests/Info.plist
quickstart/objectivec-ios/helloworld/helloworldUITests/helloworldUITests.m

Update quickstart for iOS (master)

---

README.md
samples/csharp/dotnet-windows/translation-wpf/translation-wpf/MainWindow.xaml.cs
samples/csharp/sharedcontent/console/translation_samples.cs
samples/java/jre/console/src/com/microsoft/cognitiveservices/speech/samples/console/SpeechRecognitionSamples.java
samples/java/jre/console/src/com/microsoft/cognitiveservices/speech/samples/console/TranslationSamples.java
samples/js/browser/index.html

See https://docs.microsoft.com/en-us/azure/cognitive-services/speech-service/language-support

Update samples to use public voice name in translation synthesis

---

ci/build.yml

Switch away from deprecated hosted agent pool.

ci/build.yml: switch pool "Hosted Linux Preview" -> "Hosted Ubuntu 1604"

---

README.md
quickstart/cpp-windows/helloworld/helloworld.vcxproj
quickstart/cpp-windows/helloworld/packages.config
quickstart/csharp-dotnet-windows/helloworld/helloworld.csproj
quickstart/csharp-dotnet-windows/helloworld/packages.config
quickstart/csharp-dotnetcore/helloworld/helloworld.csproj
quickstart/csharp-uwp/helloworld/helloworld.csproj
quickstart/java-android/app/build.gradle
quickstart/java-jre/pom.xml
quickstart/speech-translation/cpp-windows/helloworld/helloworld.vcxproj
quickstart/speech-translation/cpp-windows/helloworld/packages.config
quickstart/speech-translation/csharp-dotnet-windows/helloworld/helloworld.csproj
quickstart/speech-translation/csharp-dotnet-windows/helloworld/packages.config
quickstart/speech-translation/csharp-dotnetcore/helloworld/helloworld.csproj
quickstart/speech-translation/csharp-uwp/helloworld/helloworld.csproj
quickstart/speech-translation/java-jre/pom.xml
samples/cpp/windows/console/samples/packages.config
samples/cpp/windows/console/samples/samples.vcxproj
samples/csharp/dotnet-windows/console/samples/packages.config
samples/csharp/dotnet-windows/console/samples/samples.csproj
samples/csharp/dotnet-windows/speechtotext-wpf/speechtotext-wpf/packages.config
samples/csharp/dotnet-windows/speechtotext-wpf/speechtotext-wpf/speechtotext-wpf.csproj
samples/csharp/dotnet-windows/translation-wpf/translation-wpf/packages.config
samples/csharp/dotnet-windows/translation-wpf/translation-wpf/translation-wpf.csproj
samples/csharp/dotnetcore/console/samples/samples.csproj
samples/csharp/uwp/speechtotext-uwp/speechtotext-uwp/speechtotext-uwp.csproj
samples/java/android/sdkdemo/app/build.gradle
samples/java/jre/console/pom.xml

perl ci/patch-samples-pkg.pl 1.3.1 public_samples

---

.gitignore
samples/batch/csharp/App.config
samples/batch/csharp/batchclient.csproj
samples/batch/csharp/packages.config
samples/batch/csharp/program.cs
samples/batch/csharp/transcription_definition.cs
samples/batch/csharp/transcription_result.cs
samples/csharp/dotnet-windows/speechtotext-wpf/speechtotext-wpf/MainWindow.xaml
samples/csharp/dotnet-windows/speechtotext-wpf/speechtotext-wpf/MainWindow.xaml.cs

- added all regions to WPF sample
- added an object to parse the JSON on batch sample
- added properties to batch sample to batch URI parameters
* ...
```
[ ] Bugfix
[ ] Feature
[X] Code style update (formatting, local variables)
```

Updates to samples

---

quickstart/objectivec-macos/README.md

Fixed a broken link in the references section.
* ...
```
[] Bugfix
[ ] Feature
```

Fix Quickstart references that was 404-ing

---

samples/batch/python/README.md
samples/batch/python/python-client/main.py

update the batch python sample
```
[ ] Bugfix
[ ] Feature
```

tune batch python sample

---

samples/batch/python/python-client/main.py

Tune python batch sample

---

samples/batch/python/python-client/main.py

ignore swagger error on empty delete response body

---

README.md
samples/batch/README.md

For the benefit of https://docs.microsoft.com/samples/

Top-level README.md: use absolute links

---

samples/batch/csharp/program.cs
samples/python/console/intent_sample.py
samples/python/console/main.py
samples/python/console/speech_sample.py
samples/python/console/translation_sample.py

python & C# batch sample tune

---

samples/batch/csharp/program.cs
samples/batch/python/README.md
samples/batch/python/python-client/main.py

- output transcription id in batch sample
- allow to configure region

Batch samples: allow to configure region

---

quickstart/speech-translation/cpp-windows/helloworld/helloworld.cpp

* Removed `#include "pch.h"`, since it causes the code to break in the documentation article containing it (**Quickstart: Translate speech with the Speech SDK for C++**, https://docs.microsoft.com/azure/cognitive-services/Speech-Service/quickstart-translate-speech-cpp-windows).
```
[X] Bugfix
[ ] Feature
```

1558066: Changes in code comments

---

quickstart/python/from-blob/python-client/main.py
samples/batch/python/python-client/main.py

set properties for Python batch transcription samples

---

quickstart/cpp/windows/intent-recognition/helloworld/helloworld.cpp
quickstart/csharp/dotnet/intent-recognition/helloworld/Program.cs
quickstart/java/jre/intent-recognition/src/speechsdk/quickstart/Main.java
quickstart/python/intent-recognition/quickstart.py

* Updating Intent Recognition samples to explicitly call the LUIS homeautomation model created in the quickstart. 
```
[ ] Bugfix
[ ] Feature
[x ] Refactoring (no functional changes, no api changes)
[ x] Documentation content changes
```

Intent Recognition Updates

---

quickstart/cpp/windows/intent-recognition/helloworld/helloworld.cpp
quickstart/csharp/dotnet/from-blob/program.cs
quickstart/csharp/dotnet/from-file/helloworld/Program.cs
quickstart/csharp/dotnet/from-microphone/helloworld/Program.cs
quickstart/csharp/dotnet/intent-recognition/helloworld/Program.cs
quickstart/csharp/dotnet/text-to-speech/helloworld/Program.cs
quickstart/csharp/dotnet/translate-speech-to-text/helloworld/Program.cs
quickstart/csharp/dotnetcore/from-microphone/helloworld/Program.cs
quickstart/csharp/dotnetcore/text-to-speech/helloworld/Program.cs
quickstart/csharp/dotnetcore/translate-speech-to-text/helloworld/Program.cs
quickstart/java/jre/intent-recognition/src/speechsdk/quickstart/Main.java
quickstart/python/intent-recognition/quickstart.py

Hi @BrianMouncer,
Please review these changes and merge when you approve.
I'm adding details for several quickstarts on how to add an entire LUIS model, instead of individual intents. Miscellaneous clean up and simplifications.

Added Java, C#, C++ and Python updates

---

quickstart/javascript/browser/index-from-file.html
quickstart/javascript/browser/index-from-mic.html
quickstart/javascript/browser/index-intent-recognition.html
quickstart/javascript/browser/index-multiple-langs.html
quickstart/javascript/browser/index-sts.html
quickstart/javascript/browser/index-translate-stt.html
quickstart/javascript/browser/index-tts.html

Adding html files to reference in docs.
```
[ ] Bugfix
[ ] Feature
```

adding html files

---

quickstart/javascript/browser/from-file/README.md
quickstart/javascript/browser/from-microphone/README.md
quickstart/javascript/browser/intent-recognition/README.md
quickstart/javascript/browser/multi-device-conversation/README.md
quickstart/javascript/browser/text-to-speech/README.md
quickstart/javascript/browser/translate-speech-to-text-multiple-languages/README.md
quickstart/javascript/browser/translate-speech-to-text/README.md
samples/cpp/linux/compressed-audio-input/README.md
samples/cpp/windows/console/README.md
samples/csharp/dotnet-windows/console/README.md
samples/csharp/dotnet-windows/speechtotext-wpf/README.md
samples/csharp/dotnet-windows/translation-wpf/README.md
samples/csharp/dotnetcore/console/README.md
samples/csharp/unity/VirtualAssistantPreview/README.md
samples/csharp/uwp/speechtotext-uwp/README.md
samples/csharp/uwp/texttospeech-uwp/README.md
samples/csharp/uwp/virtualassistant-uwp/README.md
samples/csharp/xamarin/kws-xamarin/README.md
samples/java/android/compressed-input/README.md
samples/java/android/sdkdemo/README.md
samples/java/jre/console/README.md
samples/js/browser/README.md
samples/objective-c/ios/README.md
samples/objective-c/ios/compressed-streams/README.md
samples/python/console/README.md
samples/unity/from-unitymicrophone/README.md
samples/unity/keywordrecognizer/README.md

This PR fixes 26 links now broken in README.md files in this repo.
* ...
From relative to explicit paths.
```
[X ] Bugfix
[ ] Feature
[X ] Documentation content changes
```

sample download links use explicit path, PHP requires curl, spelling

---

samples/batch/csharp/App.config
samples/batch/csharp/artifactkind.cs
samples/batch/csharp/batchclient.csproj
samples/batch/csharp/combinedresults.cs
samples/batch/csharp/entityerror.cs
samples/batch/csharp/entityreference.cs
samples/batch/csharp/file.cs
samples/batch/csharp/filelinks.cs
samples/batch/csharp/fileproperties.cs
samples/batch/csharp/links.cs
samples/batch/csharp/nbest.cs
samples/batch/csharp/paginatedfiles.cs
samples/batch/csharp/paginatedtranscriptions.cs
samples/batch/csharp/profanityfiltermode.cs
samples/batch/csharp/punctuationmode.cs
samples/batch/csharp/recognitionresult.cs
samples/batch/csharp/recognitionresults.cs
samples/batch/csharp/speechjsoncontractresolver.cs
samples/batch/csharp/timespanconverter.cs
samples/batch/csharp/transcriptionproperties.cs
samples/batch/csharp/worddetails.cs

recent check-in introduces BOM markers
we shouldn't have source files with BOM markers
removing BOM in subdirectory samples\batch\csharp
```
[ ] Bugfix
[ ] Feature
[ X ] Code style update (formatting, local variables)
```

remove BOM from files

---

samples/batch/transcriptionresult_v3.schema.json

Added json schema for the v3 transcription result format.
Documentation improvement.
```
[ ] Bugfix
[ ] Feature
```

added transcription result schema definition

---

samples/batch/transcriptionresult_v3.schema.json

Fix whitespace - converted tabs into spaces.
```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
```

converted tabs into spaces

---

quickstart/javascript/browser/index-multiple-langs.html
quickstart/javascript/browser/index-translate-stt.html

Retaining Chinese target, following Languages guidance about specifiers.
```
[x ] Bugfix
[ ] Feature
```

save Chinese, specify just language on targets

---

quickstart/javascript/browser/from-file/index.html

https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/884
* ...
Corrects from-file speech recognition html sample for javascript 
From file quickstart now selects a file and recognizes from that file instead of from the microphone
```
[X ] Bugfix
[ ] Feature
```

Correct from-file JS browser quickstart

---

README.md

Add missing note on the 1.14 release.
Closes #907 
```
[ ] Bugfix
[ ] Feature
```

Mention 1.14 release in main README.md

---

samples/csharp/dotnetcore/console/README.md
samples/csharp/sharedcontent/console/Program.cs

Closes #909 . Please look at issue #909 for the full details. Thanks and happy new year!
```
[x] Bugfix
[ ] Feature
```

Fix C# menu sample code. Fix .net core build command in README.md

---

samples/csharp/uwp/virtualassistant-uwp/README.md

Update UWP C# Voice Assistant README

---

samples/js/node/README.md

Minor updates to JS node sample README

---

samples/js/browser/synthesis.html

* ...
```
[ ] Bugfix
[x] Feature
```
add download synthesized audio in TTS JS sample, for #933

add download synthesized audio in TTS JS sample

---

samples/js/browser/synthesis.html

https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/933#issuecomment-768267775
* Use correct synthesis voice when downloading
```
[X] Bugfix
[ ] Feature
```

Use selected voice options value when downloading

---

samples/js/browser/synthesis.html

Address #960 , add option in JS sample to select output format
```
[ ] Bugfix
[x] Feature
```

Add option in JS sample to select output format

---

samples/js/node/README.md

The link to [this article] wasn't pointing to the js-node zone pivot. I fixed that.
* ...
```
[ ] Bugfix
[ ] Feature
```

Updated a link

---

samples/js/browser/index.html

pronunciation assessment JavaScript browser sample
```
[ ] Bugfix
[x] Feature
```

pronunciation assessment JavaScript browser sample

---

quickstart/csharp/uwp/translate-speech-to-text/README.md

old one gave 404
* ...
```
[ ] Bugfix
[ ] Feature
```

Updated quickstart link

---

quickstart/cpp/windows/translate-speech-to-text/README.md

Was pointed to old link, got 404
* ...
```
[ ] Bugfix
[ ] Feature
```

Updated URL to doc

---

quickstart/csharp/dotnet/translate-speech-to-text/README.md

old one gave 404
* ...
```
[ ] Bugfix
[ ] Feature
```

Updated link to quickstart

---

samples/js/browser/synthesis.html

* ...
Update TTS JavaScript browser sample
- [feature] add sample for viseme and bookmark event
- [bug] fix the downloaded audio is not playable for riff* format
```
[x] Bugfix
[x] Feature
```

update TTS JS browser sample

---

samples/ingestion/ingestion-client/RealtimeTranscription/RealtimeTranscription.cs

* ...
```
[x ] Bugfix
[ ] Feature
```

Add silence timeout for realtime transcription azure function

---

samples/ingestion/ingestion-client/RealtimeTranscription/Helpers/RealtimeTranscriptionHelper.cs
samples/ingestion/ingestion-client/Tests/EndToEndTests.cs

* ...
```
[ ] Bugfix
[ ] Feature
```

Fix realtime transcription helper bug

---

samples/ingestion/ingestion-client/Setup/ArmTemplateRealtime.json

* ...
```
[ ] Bugfix
[ ] Feature
```

Update max delivery count in realtime mode

---

samples/python/console/main.py
samples/python/console/speech_language_detection_sample.py

Add SourceLanguageRecognizer python sample with Speech SDK 1.1.8.0 release
SourceLanguageRecognizer python samples
```
[ ] Bugfix
[x] Feature
```

Add SourceLanguageRecognizer python sample

---

samples/csharp/sharedcontent/console/helper.cs
samples/csharp/sharedcontent/console/speech_synthesis_samples.cs
samples/csharp/sharedcontent/console/speech_synthesis_server_scenario_sample.cs
samples/java/jre/console/src/com/microsoft/cognitiveservices/speech/samples/console/SpeechSynthesisScenarioSamples.java

1. add latency number to tts sample
2. update comments of server sample
```
[ X] Bugfix
[ ] Feature
```

update tts samples

---

samples/ingestion/ingestion-client/Setup/ArmTemplateBatch.json

* ...
```
[ ] Bugfix
[ ] Feature
```

[Ingestion Client] Add database connection string to keyvault

---

samples/js/browser/synthesis.html

* ...
```
[ ] Bugfix
[ ] Feature
```

update region list in tts js sample to latest

---

quickstart/cpp/windows/translate-speech-to-text/README.md
quickstart/csharp/dotnet/translate-speech-to-text/README.md
quickstart/csharp/uwp/translate-speech-to-text/README.md
quickstart/java/jre/translate-speech-to-text/README.md
samples/csharp/unity/VirtualAssistantPreview/README.md

LInk fixes done incorrectly in pull request 1087, done right here.
```
[ ] Bugfix
[ ] Feature
```

proper link updates

---

samples/ingestion/ingestion-client/Setup/ArmTemplateBatch.json

* Modifies the ARM template to enable deployments to Azure Gov regions (arizona and virginia)
```
[ ] Bugfix
[x] Feature
```

[Ingestion Client] Add Azure Gov support to ARM template

---

samples/ingestion/ingestion-client/Setup/ArmTemplateBatch.json

```
[x] Bugfix
[ ] Feature
```

[Ingestion Client] Make deployment auth rules sequential

---

samples/ingestion/ingestion-client/Connector/BatchClient.cs
samples/ingestion/ingestion-client/Connector/Connector.csproj
samples/ingestion/ingestion-client/Connector/ModelIdentity.cs
samples/ingestion/ingestion-client/FetchTranscription/TranscriptionProcessor.cs
samples/ingestion/ingestion-client/Setup/ArmTemplateBatch.json
samples/ingestion/ingestion-client/StartTranscriptionByServiceBus/StartTranscriptionByServiceBus.csproj
samples/ingestion/ingestion-client/StartTranscriptionByTimer/StartTranscriptionEnvironmentVariables.cs
samples/ingestion/ingestion-client/StartTranscriptionByTimer/StartTranscriptionHelper.cs

Adds the option to connect to a custom endpoint (like https://mycustomendpoint.cognitiveservices.azure.com/ instead of 
* ...
```
[ ] Bugfix
[x] Feature
```

[Ingestion Client] Enable custom endpoints

---

samples/ingestion/ingestion-client/FetchTranscription/host.json

Set fetch function timeout to 10 minutes to allow dynamic app service plans
```
[ ] Bugfix
[x] Feature
```

[Ingestion Client] Set fetch function timeout to 10 minutes

---

samples/js/browser/public/index.html

See https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1252
* ...
```
[x ] Bugfix
[ ] Feature
```

Add us gov regions to JS browser sample

---

ThirdPartyNotices.md
samples/cpp/windows/console/samples/packages.config
samples/cpp/windows/console/samples/samples.vcxproj
samples/cpp/windows/console/samples/speech_recognition_samples.cpp
samples/csharp/sharedcontent/console/Program.cs
samples/csharp/sharedcontent/console/speech_recognition_samples.cs
samples/java/jre/console/pom.xml
samples/java/jre/console/src/com/microsoft/cognitiveservices/speech/samples/console/Main.java
samples/java/jre/console/src/com/microsoft/cognitiveservices/speech/samples/console/SpeechRecognitionSamples.java
samples/python/console/main.py
samples/python/console/speech_sample.py

Samples for detailed reco results, including word-level timing (C++, C#, Java, Python)
This is a copy of the changes already made and reviewed in our internal repo.

Samples for detailed reco results, including word-level timing

---

samples/cpp/windows/console/samples/intent_recognition_samples.cpp
samples/cpp/windows/console/samples/main.cpp
samples/cpp/windows/console/samples/samples.vcxproj

Added sample for the Intent Recognizer changes released in 1.19
```
[ ] Bugfix
[x] Feature
```

updated with Intent recognition pattern matching sample

---

samples/cpp/windows/console/samples/intent_recognition_samples.cpp

* ...
* Just refactored some code to line up with internal guidelines
```
[ ] Bugfix
[ ] Feature
```

some code style refactoring

---

quickstart/java/jre/from-blob/pom.xml
quickstart/java/jre/virtual-assistant/pom.xml

* This PR updates dependencies from some of the Java quickstarts.
```
[X] Bugfix
[ ] Feature
```

Fixing dependency vulnerabilities

---

quickstart/java/jre/virtual-assistant/pom.xml

to avoid critical issue CVE-2021-27568
closes #1347

Update to latest bot-builder Java package

---

samples/cpp/windows/console/samples/speech_synthesis_samples.cpp
samples/csharp/sharedcontent/console/speech_synthesis_samples.cs
samples/csharp/sharedcontent/console/speech_synthesis_server_scenario_sample.cs
samples/java/android/SpeechSynthesis/app/src/main/java/com/microsoft/cognitiveservices/speech/samples/speechsynthesis/MainActivity.java
samples/java/jre/console/src/com/microsoft/cognitiveservices/speech/samples/console/SpeechSynthesisSamples.java
samples/js/browser/public/synthesis.html
samples/js/browser/synthesis.html
samples/js/node/synthesis.js
samples/objective-c/ios/synthesis-samples/synthesis-samples/ViewController.m
samples/python/console/speech_synthesis_sample.py

Per Melinda Ma let's use en-US-JennyNeural for these examples
```
[ ] Bugfix
[ ] Feature
```

jennyneural examples

---

samples/java/jre/console/src/com/microsoft/cognitiveservices/speech/samples/console/Main.java
samples/java/jre/console/src/com/microsoft/cognitiveservices/speech/samples/console/SpeechRecognitionSamples.java

update pronunciation assessment java sample
- add a sample with stream input
```
[ ] Bugfix
[x] Feature
```

update pronunciation assessment java sample

---

quickstart/cpp/windows/intent-recognition/helloworld/helloworld.cpp
quickstart/csharp/dotnet/intent-recognition/helloworld/Program.cs
quickstart/csharp/uwp/from-microphone/helloworld/MainPage.xaml.cs
quickstart/java/jre/intent-recognition/src/speechsdk/quickstart/Main.java
quickstart/python/intent-recognition/quickstart.py

Add snippet tags to quickstarts so that docs can use them instead of ranges (which are currently broken).
```
[ ] Bugfix
[ ] Feature
```

Add snippet tags

---

docs/pronunciationassessment/how-to-get-phonemes-in-ipa-format.md
docs/pronunciationassessment/how-to-get-spoken-phonemes.md
docs/pronunciationassessment/how-to-get-syllables.md

Recently we released some new features of pronunciation assessment.
We want to put some docs to help developers learn about how to use these features.
```
[ ] Bugfix
[ ] Feature
```

Add how-to guidance for phonetic assessment features for Pronunciation Assessment API

---

samples/batch/python/README.md
samples/batch/python/python-client/main.py

minor edits to batch Python sample

---

samples/ingestion/ingestion-client/Setup/ArmTemplateBatch.json

Change Fetch transcription max. delivery count
```
[x] Bugfix
[ ] Feature
```

[Ingestion Client] Change Fetch transcription max. delivery count

---

samples/js/browser/index.html

Add Central India region in drop down list of regions available in js browser sample.
Additional option.
```
[ ] Bugfix
[ ] Feature
[x ] Other... Please describe: Added option in drop down list.
```

add Central India Region to js browser

---

samples/batch/python/README.md

change swagger url for CRIS REST API

---

quickstart/csharp/unity/text-to-speech/Assets/Scripts/HelloWorld.cs

* Update TTS Unity quick start sample code to support streaming
```
[ ] Bugfix
[ ] Feature
```

Update TTS Unity quick start sample code to support streaming

---

samples/batch/python/python-client/main.py

* adapt batch transcription sample to changed swagger file source

adapt sample to swagger file change

---

quickstart/cpp/windows/speaker-recognition/README.md
quickstart/csharp/dotnet/speaker-recognition/README.md
quickstart/java/jre/speaker-recognition/README.md
quickstart/javascript/browser/speaker-recognition/identification/README.md
quickstart/javascript/browser/speaker-recognition/verification/README.md
quickstart/javascript/node/speaker-recognition/identification/README.md
quickstart/javascript/node/speaker-recognition/verification/README.md

* Speaker Recognition access is gated (and we get a steady cadence of "why can't I connect to SID" issues). Add a prominent note in the quickstart, with links for requesting access
```
[ ] Bugfix
[ ] Feature
```

Add Speaker Recognition limited access verbiage

---

quickstart/csharp/dotnet/speaker-recognition/helloworld/helloworld.csproj
samples/csharp/dotnetcore/console/samples/samples.csproj
samples/csharp/sharedcontent/console/Program.cs
samples/csharp/sharedcontent/console/speech_synthesis_samples.cs
samples/csharp/sharedcontent/console/test.txt

customer has need to synthesize long text that is over 10 minute limits. 
we can break the text into paragraphes and use SDK to synthesize it into one mp3 file. 
[ ] Bugfix
[X] Feature
```

add a long file synthesis sample

---

scenarios/cpp/windows/captioning/readme.md

* Suggested edits to the CPP readme
```
[ ] Bugfix
[ ] Feature
```

suggested edits

---

samples/ingestion/ingestion-client/FetchTranscription/TranscriptionProcessor.cs

Wrong ServiceBusSender was referenced
```
[x] Bugfix
[ ] Feature
```

[Ingestion Client] Fix wrong ServicesBusSender reference in TranscriptionProcessor

---

samples/java/android/sdkdemo/app/src/main/java/com/microsoft/cognitiveservices/speech/samples/sdkdemo/MainActivity.java

Clarify comments about microphone audio config in Android sample code as raised in the issue https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/1471.
```
[ ] Bugfix
[ ] Feature
```

Update comments for microphone audio config in Android sample MainActivity.java

---

samples/ingestion/ingestion-client/Connector/Serializable/TranscriptionStartedMessage/TextAnalyticsRequest.cs
samples/ingestion/ingestion-client/Connector/Serializable/TranscriptionStartedMessage/TextAnalyticsRequests.cs

* Remove BOM in TextAnalytics files
* 
```
[x] Bugfix
[ ] Feature
```

[IngestionClient] Remove BOM in TextAnalytics files

---

quickstart/javascript/browser/translate-speech-to-text/index.html

* ...
```
[ ] Bugfix
[ ] Feature
```

Update Text for Translation Button.js

---

samples/java/jre/console/src/com/microsoft/cognitiveservices/speech/samples/console/SpeechRecognitionSamples.java

Se issue #1606 
[ ] Bugfix
[ ] Feature
[x] Other... Please describe:
Add clarity to the Java PushStream sample
```

Add text on wav format for clarity

---

scenarios/python/console/captioning/helper.py

helper.py was missing an import statement. See issue #1601 
```
[X] Bugfix
[ ] Feature
```

Add import for Path

---

docs/pronunciationassessment/how-to-get-phonemes-in-ipa-format.md
samples/python/console/main.py
samples/python/console/speech_language_detection_sample.py
samples/python/console/translation_sample.py

Copy over these two new samples from our internal repo to the public repo, as there is a customer request for those. They have been reviewed and signed off internally.
Also fix one minor typo in pronunciation assessment doc (unrelated to the above samples)

Add translation with LID samples

---

samples/ingestion/ingestion-client/Connector/Enums/ConversationPiiSetting.cs

Removing byte order mark from ConversationPiiSetting.cs (build failure)
```
[x] Bugfix
[ ] Feature
```

[IngestionClient] Remove ConversationPiiSetting BOM

---

samples/batch/transcriptionresult_v3.schema.json

* fix the `speaker` property in the json schema for batch transcription results

batch transcription: fix error in json schema for transcription results

---

samples/ingestion/ingestion-client/Connector/Connector.csproj

remove BOM

---

scenarios/csharp/dotnetcore/call-center/call-center/Program.cs
scenarios/csharp/dotnetcore/call-center/call-center/UserConfig.cs

Fix bug in captioning scenario.
```
[x] Bugfix
[ ] Feature
```

Updates to call center scenario.

---

scenarios/csharp/dotnetcore/call-center/call-center/Program.cs

* The timeToLive must be within "properties"
```
[X] Bugfix
[ ] Feature
```

time to live

---

samples/js/browser/index.html

Internal Ref Id 4408107
Allow voice output checkbox to set audio output from translation
* ...
```
[x ] Bugfix
[ ] Feature
```

Allow voice output checkbox to set audio output from translation

---

.github/workflows/ingestion_client.yaml

* Use raw jq output to remove quotes in version
```
[x] Bugfix
[ ] Feature
```

[IngestionClient] Use raw jq output to remove quotes in version

---

samples/ingestion/ingestion-client/FetchTranscription/TextAnalytics/TextAnalyticsProvider.cs
samples/ingestion/ingestion-client/Setup/ArmTemplateBatch.json
samples/ingestion/ingestion-client/Setup/ArmTemplateRealtime.json

Adding null check for text analytics results in case a text analytics request failed
```
[x] Bugfix
[ ] Feature
```

[Ingestion Client] Add null check on text analytics results

---

samples/cpp/embedded-speech/README.md
samples/csharp/dotnetcore/embedded-speech/README.md
samples/java/android/embedded-speech/README.md
samples/java/jre/embedded-speech/README.md

Update embedded speech sample readmes with notes about the required Speech SDK packages in a new project from scratch.
```
[ ] Bugfix
[ ] Feature
```

Add notes about required dependencies when starting a new project

---

samples/js/node/README.md
samples/js/node/filePushStream.js
samples/js/node/index.js
samples/js/node/intent.js
samples/js/node/package.json
samples/js/node/speech.js
samples/js/node/translation.js

Updated node.js sample to skip wav header
* ...
```
[X] Bugfix
[ ] Feature
```

Updated node sample to skip header

---

samples/batch-synthesis/csharp/BatchSynthesisSample/BatchSynthesisSample.csproj
samples/batch-synthesis/csharp/BatchSynthesisSample/Program.cs
samples/batch-synthesis/csharp/BatchSynthesisSample/dto/BatchSynthesisPropertiesDefinition.cs

* Update sample script to consistent with python sample.
* Update DTO to latest.
```
[ ] Bugfix
[ ] Feature
```

Update C# sample code

---

samples/ingestion/ingestion-client/FetchTranscription/Database/DatabaseConfigProvider.cs
samples/ingestion/ingestion-client/Setup/ArmTemplateBatch.json
samples/ingestion/ingestion-client/Setup/ArmTemplateRealtime.json

* Fix NRE if database was not deployed
```
[x] Bugfix
[ ] Feature
```

[IngestionClient] Fix NRE if database was not deployed

---

samples/batch/python/python-client/main.py

Auth settings key does not match the one from the swagger file, because of that the first call to perform pagination fails (first fetch of 100 entities is successful, but the next pagination call fails with 401 status code).
```
[x] Bugfix
[ ] Feature
```

[Batch] Fixing auth settings for paging in batch transcription sample

---

samples/ingestion/ingestion-client/Setup/guide.md

Update guide: Update published binary path and update pricing for premium functions
```
[ ] Bugfix
[ ] Feature
```

[IngestionClient] Update guide: Update published binary path and update pricing for premium functions

---

samples/batch/python/python-client/main.py

* We need to update the docs link, since the content moved. Docs issue reported here: https://github.com/MicrosoftDocs/azure-docs/issues/101428
```
[ ] Bugfix
[ ] Feature
```

Correct docs link

---

samples/python/console/speech_sample.py

Previous code will result in a huge mismatch between the continue mode and the short sentence mode for PA on paragraph fluency score. We weighted average the fluency score from the PA engine to reduce the mismatch.
```
[x] Bugfix
[ ] Feature
```

fix: update paragraph fluency score

---

samples/python/console/speech_sample.py

Fix the completeness score and remove useless code.
```
[x] Bugfix
[ ] Feature
```

update paragraph completeness score

---

ci/build.yml
samples/batch/csharp/README.md
samples/batch/csharp/batchclient/BatchClient.csproj
samples/batch/csharp/batchclient/batchclient.cs
samples/batch/csharp/batchclient/dto/diarizationproperties.cs
samples/batch/csharp/batchclient/dto/diarizationspeakersproperties.cs
samples/batch/csharp/batchclient/dto/displayword.cs
samples/batch/csharp/batchclient/dto/languageidentificationproperties.cs
samples/batch/csharp/batchclient/dto/nbest.cs
samples/batch/csharp/batchclient/dto/transcriptionproperties.cs
samples/batch/csharp/batchclient/dto/webhook.cs
samples/batch/csharp/batchclient/program.cs
samples/batch/csharp/webhookreceiver/webhookreceiver.cs
samples/batch/csharp/webhookreceiver/webhookreceiver.csproj
samples/batch/python/README.md
samples/batch/python/python-client/main.py
samples/batch/transcriptionresult_v3_1.schema.json

* ...
```
[ ] Bugfix
[ ] Feature
```

update batch transcription samples with API v3.1 features

---

README.md
quickstart/javascript/browser/conversation-transcription/README.md
quickstart/javascript/browser/from-file/README.md
quickstart/javascript/browser/from-microphone/README.md
quickstart/javascript/browser/intent-recognition/README.md
quickstart/javascript/browser/multi-device-conversation/README.md
quickstart/javascript/browser/speaker-recognition/identification/README.md
quickstart/javascript/browser/speaker-recognition/verification/README.md
quickstart/javascript/browser/text-to-speech/README.md
quickstart/javascript/browser/translate-speech-to-text-multiple-languages/README.md
quickstart/javascript/browser/translate-speech-to-text/README.md

This PR fixes some broken license links and a mis-description.
```
[ ] Bugfix
[ ] Feature
```

Fix README of JavaScript browser samples

---

ThirdPartyNotices.md
samples/batch-synthesis/python/synthesis.py
samples/js/node/README.md
samples/js/node/index.js
samples/js/node/package.json
samples/js/node/pronunciationAssessment.js

Provide JavaScript sample code for Pronunciation Assessment
```
[ ] Bugfix
[x] Feature
```

js sample code for pronunciation assessment

---

samples/cpp/windows/console/samples/main.cpp
samples/cpp/windows/console/samples/samples.vcxproj
samples/cpp/windows/console/samples/speech_recognition_samples.cpp

Pronunciation assessment with stream for C++ language
* ...
```
[ ] Bugfix
[x] Feature
```

Pronunciation assessment with stream for C++ language

---

samples/ingestion/ingestion-client/FetchTranscription/FetchTranscriptionEnvironmentVariables.cs
samples/ingestion/ingestion-client/Setup/ArmTemplateBatch.json
samples/ingestion/ingestion-client/Setup/ArmTemplateRealtime.json

* Fixing bug where FetchTranscriptionFunction initialization would crash if ConversationSummarizationOptions is not set
```
[x] Bugfix
[ ] Feature
```

Fix ConversationSummarizationOptions initialization

---

samples/cpp/embedded-speech/samples/settings.cpp
samples/csharp/dotnetcore/embedded-speech/samples/Settings.cs
samples/java/android/embedded-speech/app/build.gradle
samples/java/jre/embedded-speech/src/com/microsoft/cognitiveservices/speech/samples/embedded/Settings.java

Update code examples to reflect the current defaults for profanity masking, and add `@aar` package specifier in the Android sample build config.
```
[ ] Bugfix
[ ] Feature
[x] Other improvement
```

Update embedded speech samples

---

sampledata/customspeech/en-US/biology/training/pronunciation.txt

Update pronunciation.txt sample data
Update pronunciation.txt sample data
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Update pronunciation.txt sample data
```

[Custom Speech] Update pronunciation.txt sample data

---

samples/batch/python/python-client/main.py

- Fix the batch transcription sample; there was an error in the part on transcriptions with a custom model.

[batch] fix transcription with custom model sample

---

samples/java/android/embedded-speech/app/build.gradle

Add `@aar` package specifier to the embedded speech Android sample build config.
```
[ ] Bugfix
[ ] Feature
[x] Other
```

Update embedded speech Android sample package version

---

samples/js/node/filePushStream.js
samples/js/node/intent.js
samples/js/node/speech.js
samples/js/node/translation.js

Update NodeJS Sample to read wave file header to determine format, and correctly create push stream.
[X] Bugfix
[ ] Feature
```
Tested with 16Khz, 8Khz alaw and mulaw files.

Update NodeJS Sample to read wave file header to determine format,

---

samples/ingestion/ingestion-client/Connector/Enums/TranscriptionAnalyticsJobStatus.cs
samples/ingestion/ingestion-client/FetchTranscription/Extensions/TranscriptionStartedMessageExtensions.cs
samples/ingestion/ingestion-client/FetchTranscription/TranscriptionProcessor.cs
samples/ingestion/ingestion-client/Setup/ArmTemplateBatch.json
samples/ingestion/ingestion-client/Setup/ArmTemplateRealtime.json

* Refactor the transcription analytics job to prepare adding new kinds of analytics
```
[ ] Bugfix
[ ] Feature
```

Refactor transcription analytics status check

---

quickstart/javascript/node/conversation-transcription/index.js

* ...
```
[ ] Bugfix
[ ] Feature
```

Update index.js - correct bad voice signature json

---

samples/ingestion/ingestion-client/Setup/ArmTemplateBatch.json

This PR fixes a bug where the deployment of the ARM template would fail with error:
```json
"details": [
{
"code": "NotFound",
"message": "The requested resource FetchTranscription does not exist."
}
]
```
See #2038
```
[x] Bugfix
[ ] Feature
```

[IngestionClient] Fix "Resource does not exist" deployment error in ARM template

---

.github/workflows/label-stale-issues.yml

This workflow will run once, daily M-F and label items that have had no recent activity with "update needed" and add a comment requesting an update from the dev team.
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe:
```

Create auto-labeler for stale issues

---

.github/workflows/label-stale-issues.yml

Minor formatting update (and also updating to the correct year 😁)

Fix datetime format

---

.github/workflows/label-stale-issues.yml

* ...
```
[ ] Bugfix
[ ] Feature
```

Use update action template

---

.github/workflows/label-stale-issues.yml

Debug runs passed! Enabling for daily runs

Enliven the Auto-labeler

---

sampledata/customavatar/verbal-statement-all-locales.txt

Add custom avatar verbal statement templates
[ ] Bugfix
[ ] Feature

[TalkingAvatar] Add custom avatar verbal statement templates

---

ThirdPartyNotices.md
samples/java/jre/console/pom.xml
samples/java/jre/console/src/com/microsoft/cognitiveservices/speech/samples/console/Main.java
samples/java/jre/console/src/com/microsoft/cognitiveservices/speech/samples/console/SpeechRecognitionSamples.java

adding PA continuous mode for JRE(Java)
```
[ ] Bugfix
[x] Feature
```

adding PA continuous mode for JRE(Java)

---

sampledata/customspeech/en-US/display formatting/training/data_display format.txt
sampledata/customspeech/en-US/display formatting/training/data_text.txt

Upload the sample data for CDPP
Sample data update.
```
[ ] Bugfix
[ ] Feature
```

Upload the sample data for CDPP

---

samples/batch-avatar/python/synthesis.py
samples/batch-synthesis/csharp/BatchSynthesisSample/Program.cs
samples/batch-synthesis/python/synthesis.py
samples/cpp/windows/console/samples/speech_synthesis_samples.cpp
samples/csharp/sharedcontent/console/speech_synthesis_samples.cs
samples/csharp/sharedcontent/console/speech_synthesis_server_scenario_sample.cs
samples/java/android/SpeechSynthesis/app/src/main/java/com/microsoft/cognitiveservices/speech/samples/speechsynthesis/MainActivity.java
samples/java/jre/console/src/com/microsoft/cognitiveservices/speech/samples/console/SpeechSynthesisSamples.java
samples/java/jre/console/src/com/microsoft/cognitiveservices/speech/samples/console/SpeechSynthesisScenarioSamples.java
samples/js/browser/public/synthesis.html
samples/js/browser/synthesis.html
samples/js/node/synthesis.js
samples/kotlin/android/tts-pause-example/app/src/main/java/com/microsoft/cognitiveservices/speech/samples/speechsynthesis/pauseexample/MainActivity.kt
samples/objective-c/ios/synthesis-samples/synthesis-samples/ViewController.m
samples/python/console/long-form-text-synthesis/long_form_text_synthesis.py
samples/python/console/speech_synthesis_sample.py

change the recommended voice to AndrewNeural.
```
[ ] Bugfix
[ ] Feature
```

TTS - change specified voice

---

quickstart/csharp/xamarin/helloworld/helloworld.Android/Properties/AndroidManifest.xml
quickstart/csharp/xamarin/helloworld/helloworld.Android/helloworld.Android.csproj
samples/csharp/xamarin/kws-xamarin/kws-xamarin/kws-xamarin.Android/Properties/AndroidManifest.xml
samples/csharp/xamarin/kws-xamarin/kws-xamarin/kws-xamarin.Android/kws-xamarin.Android.csproj
samples/csharp/xamarin/kws-xamarin/kws-xamarin/kws-xamarin.UWP/kws-xamarin.UWP.csproj

* ...
```
[x] Bugfix
[ ] Feature
```

bump up target android version to fix ci

---

quickstart/cpp/linux/text-to-speech/helloworld.cpp
quickstart/cpp/macos/text-to-speech/helloworld.cpp
quickstart/cpp/windows/text-to-speech/helloworld/helloworld.cpp
quickstart/csharp/dotnet/text-to-speech/helloworld/Program.cs
quickstart/csharp/dotnetcore/text-to-speech/helloworld/Program.cs
quickstart/java/jre/text-to-speech/src/speechsdk/quickstart/Main.java
quickstart/python/text-to-speech/quickstart.py
samples/batch-synthesis/csharp/BatchSynthesisSample/Program.cs
samples/batch-synthesis/python/synthesis.py
samples/cpp/windows/console/samples/speech_synthesis_samples.cpp
samples/csharp/sharedcontent/console/speech_synthesis_samples.cs
samples/csharp/sharedcontent/console/speech_synthesis_server_scenario_sample.cs
samples/java/android/SpeechSynthesis/app/src/main/java/com/microsoft/cognitiveservices/speech/samples/speechsynthesis/MainActivity.java
samples/java/jre/console/src/com/microsoft/cognitiveservices/speech/samples/console/SpeechSynthesisSamples.java
samples/java/jre/console/src/com/microsoft/cognitiveservices/speech/samples/console/SpeechSynthesisScenarioSamples.java
samples/js/browser/index.html
samples/js/browser/public/index.html
samples/js/node/synthesis.js
samples/kotlin/android/tts-pause-example/app/src/main/java/com/microsoft/cognitiveservices/speech/samples/speechsynthesis/pauseexample/MainActivity.kt
samples/objective-c/ios/synthesis-samples/synthesis-samples/ViewController.m
samples/python/console/long-form-text-synthesis/long_form_text_synthesis.py
samples/python/console/speech_synthesis_sample.py

Change the recommended voice: 
- Use `en-US-AndrewNeural` only when showing how to set the voice
- Use `en-US-AvaNeural` in other scenarios
```
[ ] Bugfix
[ ] Feature
```

TTS - change recommended en-US voice

---

samples/custom-voice/python/customvoice/training_set.py
samples/custom-voice/python/personal_voice_sample.py

1. Use new personal voice base model DragonLatestNeural.
2. Service renamed trainingset.properties.size as utteranceCount.
```
[ ] Bugfix
[x] Feature
```

Update Custom Voice API sample code.

---

.github/workflows/ingestion_client.yaml

* Set package write permission to github action
```
[x] Bugfix
[ ] Feature
```

[IngestionClient] Set package write permission to github action

---

.github/workflows/ingestion_client.yaml

* Set contents: write permission on Github Action
```
[x] Bugfix
[ ] Feature
```

[IngestionClient] Set contents: write permission on Github Action

---

ThirdPartyNotices.md
samples/js/node/package.json
samples/js/node/pronunciationAssessmentContinue.js

* fix word segmentation bug when used on zh-CN
```
[X] Bugfix
[ ] Feature
```

[JS] fix word segmentation bug when used on zh-CN

---

samples/js/browser/avatar/README.md
samples/js/browser/avatar/basic.html
samples/js/browser/avatar/chat.html
samples/js/browser/avatar/js/basic.js
samples/js/browser/avatar/js/chat.js

* ...
```
[ ] Bugfix
[ ] Feature
```

[Live Avatar] Add private endpoint and personal voice speaker profile ID.

---

samples/custom-voice/README.md

Add c# client sample in readme.
```
[ ] Bugfix
[ ] Feature
```

update custom voice sample readme

---

samples/batch-synthesis/python/README.md
samples/batch-synthesis/python/synthesis.py

* ...
```
[ ] Bugfix
[ ] Feature
```

update batch synthesis python sample with passwordless auth

---

samples/js/browser/avatar/basic.html
samples/js/browser/avatar/chat.html

* ...
```
[ ] Bugfix
[ ] Feature
```

[Live Avatar] Changed TTS voice from Jenny to Avamultilingual.

---

samples/batch-synthesis/java/.gitignore
samples/batch-synthesis/java/pom.xml
samples/batch-synthesis/java/src/main/java/com/micosoft/api/axample/BatchSynthesis.java

* ...
```
[ ] Bugfix
[ ] Feature
```

add java BatchSynthesis

---

samples/python/web/avatar/README.md
samples/python/web/avatar/app.py
samples/python/web/avatar/basic.html
samples/python/web/avatar/static/js/basic.js

* ...
Support setting background image for live avatar python sample
```
[ ] Bugfix
[x] Feature
```

[Talking Avatar][Live] Support setting background image for python sample

---

quickstart/cpp/windows/from-file/README.md
quickstart/cpp/windows/from-file/helloworld/helloworld.vcxproj
quickstart/cpp/windows/from-file/helloworld/helloworld.vcxproj.filters
quickstart/cpp/windows/from-microphone/helloworld/helloworld.vcxproj
quickstart/cpp/windows/intent-recognition/helloworld/helloworld.vcxproj
quickstart/cpp/windows/multi-device-conversation/helloworld/helloworld.vcxproj
quickstart/cpp/windows/speaker-recognition/helloworld/helloworld.vcxproj
quickstart/cpp/windows/text-to-speech/helloworld/helloworld.vcxproj
quickstart/cpp/windows/translate-speech-to-text/helloworld/helloworld.vcxproj
samples/batch-avatar/csharp/BatchAvatarSample/BatchAvatarSample/dto/BatchAvatarJob.cs
samples/batch-avatar/python/synthesis.py
samples/batch-synthesis/python/synthesis.py

* ...
```
[ ] Bugfix
[ ] Feature
```

update batch avatar sample input kind option

---

samples/swift/ios/speech-samples/speech-samples/ViewController.swift

This remove unnecessary semicolon in Swift.
```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
```

Remove unnecessary semicolon

---

samples/ingestion/ingestion-client/Setup/guide.md

This PR replaces the instructions for manual copying and pasting of ARM templates into the Azure portal with one-click deploy buttons. 
```
[ ] Bugfix
[ ] Feature
```

Add one-click deploy to Azure for ingestion client.

---

samples/ingestion/ingestion-client/README.md
samples/ingestion/ingestion-client/Setup/guide.md

* Realtime ingestion client was deleted, but is still referenced in the guide. Fixing that now.
```
[x] Bugfix
[ ] Feature
```

 [IngestionClient] Clean up realtime ingestion client guide

---

.github/workflows/ingestion_client.yaml
samples/ingestion/ingestion-client/.devcontainer/devcontainer.json
samples/ingestion/ingestion-client/Connector/Connector.csproj
samples/ingestion/ingestion-client/DatabaseMigrator/DatabaseMigrator.csproj
samples/ingestion/ingestion-client/FetchTranscription/FetchTranscription.csproj
samples/ingestion/ingestion-client/StartTranscriptionByServiceBus/StartTranscriptionByServiceBus.csproj
samples/ingestion/ingestion-client/StartTranscriptionByTimer/StartTranscriptionByTimer.csproj
samples/ingestion/ingestion-client/Tests/Tests.csproj

* Move from net6.0 to net8.0, see https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/2458
```
[ ] Bugfix
[x] Feature
```

[IngestionClient] Move from net6.0 to net8.0, add pr build

---

samples/ingestion/ingestion-client/Connector/Connector.csproj
samples/ingestion/ingestion-client/DatabaseMigrator/DatabaseMigrator.csproj
samples/ingestion/ingestion-client/Directory.Build.props
samples/ingestion/ingestion-client/FetchTranscription/FetchTranscription.csproj
samples/ingestion/ingestion-client/StartTranscriptionByServiceBus/StartTranscriptionByServiceBus.csproj
samples/ingestion/ingestion-client/StartTranscriptionByTimer/StartTranscriptionByTimer.csproj
samples/ingestion/ingestion-client/Tests/Tests.csproj
samples/ingestion/ingestion-client/versions.nugets.props

*  Refactor - move package versions to props file
```
[ ] Bugfix
[ ] Feature
```

[IngestionClient] Refactor - move package versions to props file

---

samples/ingestion/ingestion-client/Setup/ArmTemplateBatch.json
samples/ingestion/ingestion-client/Tests/EndToEndTests.cs
samples/ingestion/ingestion-client/versions.nugets.props

* Update nuget packages to latest stable
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Package version updates
```

[Ingestion Client] Update nuget packages to latest stable

---

samples/ingestion/ingestion-client/.devcontainer/devcontainer.json

Add the required extensions for C# and Azure Functions into the DevContainer and respect the .editorconfig file that is already present.
```
[ ] Bugfix
[ ] Feature
```
This change effects no code, it sets up the necessary tools for developers to contribute to this project.

[IngestionClient]: IDE Settings for using Ingestion Client in vscode

---

samples/ingestion/ingestion-client/Setup/ArmTemplateBatch.json
samples/ingestion/ingestion-client/versions.nugets.props

The Function is now an Isolated Worker Function - therefore remove this key
```
[x] Bugfix
[ ] Feature
```

Remove FUNCTIONS_INPROC_NET8_ENABLED

---

samples/ingestion/ingestion-client/Setup/ArmTemplateBatch.json

The GitHub Release is not working at the moment as the version number has not been updated
```
[x] Bugfix
[ ] Feature
```

[IngestionClient]: Increment version number

---

samples/ingestion/ingestion-client/FetchTranscription/Config/AppConfig.cs

Building in Release fails because of an unused private variable. Remove the private variable
```
[x] Bugfix
[ ] Feature
```

[IngestionClient] Remove private maxPollingDelayInMinutes

---

samples/ingestion/ingestion-client/infra/main.bicep
samples/ingestion/ingestion-client/infra/main.json

Cannot create a version as it already exists
```
[x] Bugfix
[ ] Feature
```

[Ingestion Client] Update Version

---

samples/batch-avatar/csharp/BatchAvatarSample/BatchAvatarSample/Program.cs
samples/batch-avatar/python/synthesis.py

* ...
```
[ ] Bugfix
[ ] Feature
```

[batch-avatar] bump up api version to `2024-08-01`

---

samples/ingestion/ingestion-client/FetchTranscription/Program.cs
samples/ingestion/ingestion-client/StartTranscriptionByServiceBus/Program.cs
samples/ingestion/ingestion-client/StartTranscriptionByTimer/Program.cs
samples/ingestion/ingestion-client/infra/main.bicep
samples/ingestion/ingestion-client/infra/main.json

Ingestion client deployment using ARM template is broken since environment variables are not picked up by the appconfig, see https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/2524. With this PR, appsettings should get picked up from env vars as well as settings.json
```
[x] Bugfix
[ ] Feature
```

[IngestionClient] Fix environment variable setup for azure deployment

---

.github/workflows/ingestion_client.yaml
samples/ingestion/ingestion-client/FetchTranscription/Program.cs
samples/ingestion/ingestion-client/StartTranscriptionByServiceBus/Program.cs
samples/ingestion/ingestion-client/StartTranscriptionByTimer/Program.cs
samples/ingestion/ingestion-client/infra/main.bicep
samples/ingestion/ingestion-client/infra/main.json

Missed updating serviceConfig in previous PR: https://github.com/Azure-Samples/cognitive-services-speech-sdk/pull/2525
Should fix issue https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/2524
```
[x] Bugfix
[ ] Feature
```

[IngestionClient] Fix ingestion client app config

---

samples/PersonalVoice.md

Fix personal voice sample code URL link error.
```
[ ] Bugfix
[ ] Feature
```

Fix personal voice sample code URL link error.

---

ci/build.yml
samples/java/android/avatar/app/build.gradle
samples/java/android/avatar/build.gradle
samples/java/android/avatar/gradle/wrapper/gradle-wrapper.properties

* ...
```
[x] Bugfix
[ ] Feature
```

[avatar sample] drop jcenter

---

samples/ingestion/ingestion-client/Connector/BatchClient.cs
samples/ingestion/ingestion-client/FetchTranscription/Config/AppConfig.cs
samples/ingestion/ingestion-client/FetchTranscription/FetchTranscription.cs
samples/ingestion/ingestion-client/FetchTranscription/Program.cs
samples/ingestion/ingestion-client/FetchTranscription/TranscriptionProcessor.cs
samples/ingestion/ingestion-client/StartTranscriptionByTimer/Config/AppConfig.cs
samples/ingestion/ingestion-client/StartTranscriptionByTimer/Program.cs
samples/ingestion/ingestion-client/StartTranscriptionByTimer/StartTranscriptionHelper.cs
samples/ingestion/ingestion-client/infra/main.bicep
samples/ingestion/ingestion-client/infra/main.json

* Use dependency injection for BatchClient
* Add User-Agent request header
See https://github.com/Azure-Samples/cognitive-services-speech-sdk/issues/2446
```
[ ] Bugfix
[x] Feature
```

[IngestionClient] Use dependency injection for BatchClient, add User-Agent request header

---

.github/workflows/ingestion_client.yaml
samples/ingestion/ingestion-client/infra/generate_arm_templates.sh
samples/ingestion/ingestion-client/infra/main.json

* Set fixed bicep version in workflow and script
```
[x] Bugfix
[ ] Feature
```

[IngestionClient] Set fixed bicep version v0.29.47 in workflow and script

---

samples/ingestion/ingestion-client/infra/main.bicep
samples/ingestion/ingestion-client/infra/main.json

* Remove language specific URL from bicep + ARM template
```
[ ] Bugfix
[x] Feature
```

[Ingestion Client] Remove language specific URL from bicep + ARM template

---

scenarios/python/console/call-center/call_center.py

* ...
Update version of API in python scenario for call center.
Fix the version of the Language Service API for Conversation Analysis e Conversation  Summary.
```
[ x ] Bugfix
[ ] Feature
```

Update api version for python call center scenario

---

samples/batch/csharp/batchclient/dto/displayword.cs
samples/batch/csharp/batchclient/dto/recognitionresult.cs
samples/batch/csharp/batchclient/dto/recognitionresults.cs
samples/batch/csharp/batchclient/dto/worddetails.cs
samples/batch/transcriptionresult_v2024-11-15.schema.json

* update schema
* update C# sample with new fields

update schema for transcription results

---

samples/csharp/maui/speech-to-text/speech-to-text/speech-to-text.csproj

* ...
```
[ ] Bugfix
[ ] Feature
```

.net 7.0 is deprecated

---

samples/realtime-api-plus/realtime-api-plus/azure_tts.py
samples/realtime-api-plus/web/package-lock.json

* ...
```
[x] Bugfix
[ ] Feature
```

[realtime-api-plus] fix docker build error

---

samples/realtime-api-plus/Dockerfile
samples/realtime-api-plus/realtime-api-plus/app.py
samples/realtime-api-plus/realtime-api-plus/gpt4o_client.py
samples/realtime-api-plus/web/src/main.ts
scenarios/full-duplex-bot/Dockerfile
scenarios/full-duplex-bot/docker-compose.yaml
scenarios/full-duplex-bot/fullduplex/azure_fast_transcription_recognizer.py
scenarios/full-duplex-bot/fullduplex/cache.py
scenarios/full-duplex-bot/fullduplex/chat_server_azure.py
scenarios/full-duplex-bot/fullduplex/oai.py
scenarios/full-duplex-bot/fullduplex/webapp.py
scenarios/full-duplex-bot/poetry.lock
scenarios/full-duplex-bot/pyproject.toml
scenarios/full-duplex-bot/readme.md

* ...
```
[x] Bugfix
[ ] Feature
```

[realtime-api-plus] fix local development

---

samples/js/browser/avatar/js/chat.js

* ...
```
[ ] Bugfix
[ ] Feature
```

update image url

---

samples/realtime-api-plus/realtime-api-plus/azure_avatar.py

* ...
```
[x] Bugfix
[ ] Feature
```

[realtime-api-plus] fix avatar failure

---

samples/java/jre/console/src/com/microsoft/cognitiveservices/speech/samples/console/SpeechRecognitionSamples.java

* Import LinkedList to use getFirst()/getLast() method
```
[x] Bugfix
[ ] Feature
```

Import LinkedList to use getFirst() method

---

samples/batch-synthesis/README.md
samples/batch-synthesis/java/pom.xml
samples/batch-synthesis/java/src/main/java/com/microsoft/api/example/BatchSynthesis.java
samples/realtime-api-plus/Dockerfile
samples/realtime-api-plus/web/package.json

* ...
Fix #2726 
```
[x] Bugfix
[ ] Feature
```

fix realtime-plus build

---

samples/python/console/speech_sample.py

* Update the initial values of "startOffset" and "endOffset".
* Handle cases where the word segmentation results are out of order.
```
[x] Bugfix
[ ] Feature
```

[PA][Python]Bug fixing

---

samples/js/browser/avatar/basic.html
samples/js/browser/avatar/chat.html
samples/js/browser/avatar/js/basic.js
samples/js/browser/avatar/js/chat.js

* ...
```
[ ] Bugfix
[ ] Feature
```

[Avatar][js] Show subtitles

---

samples/batch-synthesis/csharp/BatchSynthesisSample/BatchSynthesisClient.cs
samples/batch-synthesis/csharp/BatchSynthesisSample/Program.cs
samples/batch-synthesis/csharp/BatchSynthesisSample/README.md

* ...
```
[ ] Bugfix
[ ] Feature
```

Fix invalid legacy voice in batch synthesis sample code

---

samples/PersonalVoice.md
samples/custom-voice/README.md
samples/custom-voice/csharp/CustomVoiceSample/PersonalVoiceSample.cs
samples/custom-voice/python/personal_voice_sample.py

Update personal voice doc: support 2 more regions (West US2, East Asia)
```
[ ] Bugfix
[ ] Feature
```

Update personal voice doc: support 2 more regions.

---

samples/js/node/pronunciationAssessmentContinue.js

* Handle cases where the word segmentation results are out of order.
```
[x] Bugfix
[ ] Feature
```

[PA][JavaScript]Handle cases where the word segmentation results are out of order.

---

ThirdPartyNotices.md
samples/cpp/windows/console/samples/packages.config
samples/cpp/windows/console/samples/samples.vcxproj
samples/cpp/windows/console/samples/speech_recognition_samples.cpp
samples/csharp/sharedcontent/console/speech_recognition_samples.cs
samples/java/jre/console/src/com/microsoft/cognitiveservices/speech/samples/console/SpeechRecognitionSamples.java

Update PA content score calculation
* update PA content score calculation
* update the reference words calculation
```
[ ] Bugfix
[x] Feature
```

update PA content score calculation

---

samples/objective-c/ios/speech-samples/speech-samples/ViewController.m
samples/swift/ios/speech-samples/speech-samples/ViewController.swift

* update the pa content score calculation
```
[ ] Bugfix
[x] Feature
```

update the pa content score calculation

---

samples/csharp/web/avatar/Controllers/AvatarController.cs

* fix issue, update to FromEndpoint() method
```
[x] Bugfix
[ ] Feature
```

update to FromEndpoint

---

samples/js/node/pronunciationAssessmentContinue.js
samples/python/console/speech_sample.py

* Configure the Speech_SegmentationSilenceTimeoutMs property.
```
[ ] Bugfix
[x] Feature
```

[PA][Python][JavaScript]Configure the Speech_SegmentationSilenceTimeoutMs property.

---

samples/swift/ios/speech-samples/speech-samples/ViewController.swift

* configure a parameter for swift
* change to lower case for recognized words to compare
```
[ ] Bugfix
[x] Feature
```

configure a parameter Speech_SegmentationSilenceTimeoutMs

---

samples/csharp/web/avatar/wwwroot/js/chat.js

* Refine the auto-reconnect logic to avoid infinite reconnection
```
[ ] Bugfix
[x] Feature
```

[TTS Avatar][C#]Refine the auto-reconnect logic to avoid infinite reconnection

---

samples/objective-c/ios/speech-samples/speech-samples/ViewController.m
samples/swift/ios/speech-samples/speech-samples/ViewController.swift

* remove content score function for swift/objective c
```
[ ] Bugfix
[x] Feature
```

remove content score function for swift/objc

---

sampledata/customavatar/verbal-statement-built-in-voice-all-locales.txt

Add verbal statement of custom avatar with built-in voice
[ ] Bugfix
[ ] Feature
```

[customavatar] Create verbal-statement-built-in-voice-all-locales.txt

---

samples/python/console/chatting/chatting_sample.py

* update for chatting sample
```
[ ] Bugfix
[x] Feature
```

[Python]update for chatting sample

---

samples/video-translation/csharp/VideoTranslationSample/Program.cs

* ...
```
[ ] Bugfix
[ ] Feature
```

[VideoTranslation][csharp]Fix API client sample code bug, should not assign font to zero for default value.

---

samples/video-translation/csharp/VideoTranslationLib.Public/VideoTranslationLib.Public/DataContracts/DTOs/Public-2025-05-20/TranslationInput.cs
samples/video-translation/csharp/VideoTranslationSample/Program.cs

* ...
```
[ ] Bugfix
[ ] Feature
```

[VideoTranslation][csharp]Support lip sync and translate audio file.

---

scenarios/python/console/language-learning/.vscode/tasks.json
scenarios/python/console/language-learning/README.md
scenarios/python/console/language-learning/config.json
scenarios/python/console/language-learning/pronunciation_assessment.py

* ...
```
[ ] Bugfix
[ ] Feature
```

chore: integrate vscode ext needed files for sample Pronunciation Assessment

---

scenarios/python/console/language-learning/pronunciation_assessment.py
scenarios/python/console/language-learning/utils.py

* add function to align list
* update word errorType to Mispronunciation when accuracy score is below 60 
```
[ ] Bugfix
[x] Feature
```

adding function to align list

---

samples/js/browser/index.html
scenarios/javascript/browser/language-learning/.env
scenarios/javascript/browser/language-learning/.gitattributes
scenarios/javascript/browser/language-learning/README.md
scenarios/javascript/browser/language-learning/index.html
scenarios/javascript/browser/language-learning/package.json
scenarios/javascript/browser/language-learning/server/index.js

* move PA feature to scenarios folder
```
[ ] Bugfix
[ ] Feature
```

[JS][Browser]move PA feature to scenarios folder

---

scenarios/swift/ios/language-learning/speech-samples/ViewController.swift

* update the score calculation in swift
```
[ ] Bugfix
[x] Feature
```

update the score calculation

---

sampledata/customtn/customtn_de-de_measurement.json

custom TN rule refine for single letter unit

custom TN rule refine for single letter unit
